[project]
name = "hyrivals-bot"
version = "0.1.0"
description = "Discord bot for the Hyrivals Discord Server."
readme = "README.md"
authors = [
    { name = "Intedai", email = "arielsync@proton.me" }
]
requires-python = ">=3.13"
dependencies = [
    "discord-py>=2.6.4",
    "pillow>=12.1.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]

[project.scripts]
bot = "hyrivals_bot.main:main"

[build-system]
requires = ["uv_build>=0.10.6,<0.11.0"]
build-backend = "uv_build"
